for p in $(cat $1)
do
  folder=`echo $p|cut -c 2-3`
  pdb_name=`echo $p|awk -F'_' '{print $1 $2}'`
  fst_name=`echo $p|awk -F'_' '{print tolower($1) "_" $2}'`
  echo $p $folder $fst_name

  #get seq info
  cd fst/${folder}/
    grep -A 1 ${fst_name} ../../../database/pdb_seqres.txt > ${p}.fasta
  cd ../..

  #parse
  cd raw/${folder}/
    #clean
    #DUMMY: grep ^ATOM ${pdb_name}.pdb > ${pdb_name}_clean.pdb
    alt=$(awk '/^ATOM/ {a=substr($0,17,1);if(a>="0")print a}' ${pdb_name}.pdb | sort | uniq | head -n 1)
    python ../../../scripts/gen_fix_state.py ${pdb_name}.pdb $alt > fix.pml
    pymol -qc fix.pml
    python ../../../scripts/idealize_pdb.py ${pdb_name}.pdb > ${pdb_name}_clean.pdb

    #pdb seq, TODO: can be generated by idealizer
    ../../../bin/pdb2fasta ${pdb_name}_clean.pdb > ${pdb_name}.pdb.fst

    #alignment
    #echo python ../../../scripts/match_pdb_fasta.py ${pdb_name}.pdb.fst ../../fst/${folder}/${p}.fasta
    python ../../../scripts/match_pdb_fasta.py ${pdb_name}.pdb.fst ../../fst/${folder}/${p}.fasta > ${p}.aln

    #renumber
    python ../../../scripts/renumber_pdb.py -p ${pdb_name}_clean.pdb -l ${p}.aln -o ${pdb_name}_renumber.pdb
  cd ../..
done
